---
repos:
    - repo: https://github.com/psf/black
      rev: 21.7b0
      hooks:
          - id: black
            args: [--line-length=80, --safe]
            language_version: python3
    - repo: git://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-symlinks
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: debug-statements
          - id: check-yaml
          - id: check-ast
          - id: check-symlinks
          - id: requirements-txt-fixer
          - id: check-xml
          - id: name-tests-test
          - id: pretty-format-json
            args:
                - --autofix
                - --indent=4

          - id: fix-encoding-pragma
            args:
                - --remove
          - id: forbid-new-submodules
          - id: check-added-large-files
            args:
                - --maxkb=5000
          - id: no-commit-to-branch
            args: [--branch, staging]

    - repo: https://github.com/asottile/reorder_python_imports
      rev: v2.5.0
      hooks:
          - id: reorder-python-imports

    - repo: https://github.com/myint/docformatter
      rev: v1.4
      hooks:
          - id: docformatter
            args:
                - --in-place
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11
      hooks:
          - id: yamlfmt
            args:
                - --preserve-quotes

    - repo: https://github.com/asottile/blacken-docs
      rev: v1.10.0
      hooks:
          - id: blacken-docs
            additional_dependencies:
                - black==21.6b0

    - repo: https://github.com/myint/autoflake
      rev: v1.4
      hooks:
          - id: autoflake
            types:
                - python
            language: python
            files: \.py$
            args:
                - --in-place
                - --remove-unused-variables
                - --remove-all-unused-imports
                - --remove-duplicate-keys
                - --expand-star-imports
